languageCode = "en-us"
baseurl = "https://suri.epfl.ch/"
title = "Summer Research Institute"

[social]
    twitter = "https://twitter.com/epfl"
    mail = "dedis@epfl.ch"

[params]
    program = "false"
